server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server1  #注意：现在这个应用名是不可用的，需要到C:\Windows\System32\drivers\etc的hosts文件设置一下映射IP：127.0.0.1
  client:
    service-url:
      defaultZone: http://eureka-server2:8762/eureka  #第一个eureka server服务注册中心将自己注册到第二个eureka server服务中心
    register-with-eureka: true
    fetch-registry: true
