server:
  port: 8769

spring:
  application:
    name: hystrix_monitor  #项目应用名
eureka:
  instance:
    hostname: localhost  #主机名
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka  #连接eureka服务中心

turbine:
  combine-host-port: true
  app-config: provider,consumer  #配置需要监控的服务名称监控列表
  cluster-name-expression: "'default'"
  aggregator:
    cluster-config: default

