server:
  port: 80

spring:
  application:
    name: gateway  #项目应用名

  cloud:
    gateway:
      routes:  #路由配置，转发规则 
        - id: gateway_provider  #唯一标识,就是你要访问的服务在eureka注册中心的应用名，默认是UUID
          uri: http://localhost:8100/  #转发路径
          predicates:  #条件，用于请求网关路径的匹配规则
          - Path=/book/**

