server:
  port: 80

spring:
  application:
    name: gateway  #项目应用名

  cloud:
    gateway:
      routes:  #路由配置，转发规则 
        - id: gateway_provider  #服务提供者
          uri: http://localhost:8100/  #转发路径
          predicates:  #条件，用于请求网关路径的匹配规则
          - Path=/book/**

        - id: gateway_consumer  #服务消费者
          uri: http://localhost:8300/  #转发路径
          predicates:  #条件，用于请求网关路径的匹配规则
          - Path=/bookStore/**