server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #连接eureka服务中心

spring:
  application:
    name: gateway  #项目应用名

  cloud:
    gateway:
      routes:  #路由配置，转发规则 
        - id: gateway_provider  #服务提供者
          uri: lb://provider  #动态路由uri格式：lb://eureka应用名
          predicates:  #条件，用于请求网关路径的匹配规则
          - Path=/book/**

        - id: gateway_consumer  #服务消费者
          uri: lb://consumer  #动态路由uri格式：lb://eureka应用名
          predicates:  #条件，用于请求网关路径的匹配规则
          - Path=/bookStore/**