server:
  port: 8761

spring:
  application:
    name: eureka-server  #应用名称，会在eureka中作为服务的id标识号（serverId） 将会在eureka的Application中显示，后面需要使用该名称来获取它的访问路径

eureka:
  instance:
    hostname: localhost  #主机名
  client:
    service-url:
      defaultZone: httt://${eureka.instance.hostname}:${server.port}/eureka  #EurekaServer地址，现在是自己的地址，如果是集群，需要写其他的server地址，后面客户端使用该地址和eureka进行通信
    register-with-eureka: false #是否将自己也注册 默认是true，如果是集群，是要注册自己的
    fetch-registry: false  #表示是否拉取,默认为true， 需不需要去获取服务，如果是集群，是需要拉取服务的
  server:
    enable-self-preservation: false  # 是否开启自我保护机制，默认为true。就是有的实例没有按规定，而且超过规定的时间了没有向eureka server发送心跳包，理论上eureka server会把它这个实例剔除掉，eureka server默认开启了自我保护机制后，所以它是不会剔除掉的
    eviction-interval-timer-in-ms: 60000  #清理间隔(单位毫秒，默认是60*1000)